version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    volumes:
      - ./database:/var/lib/mysql
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=root
    ports:
      - '3307:3306'